name: example
description: An example project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dblib:
    git:
      url: https://github.com/techknowledge-dev/dblib_dart.git

#  dblib:
#    path: ../

dependency_overrides:
  collection: ^1.16.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

